package:
  name: talloc
  version: 2.1.3

source:
  fn: talloc-2.1.3.tar.gz
  url: https://www.samba.org/ftp/talloc/talloc-2.1.3.tar.gz

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python

about:
  home: https://talloc.samba.org
  license: 
  summary: talloc is a hierarchical, reference counted memory pool system with destructors. It is the core memory allocator used in Samba.
