package:
  name: ruby
  version: 2.2.3

source:
  fn: ruby-2.2.3.tar.bz2
  url: https://cache.ruby-lang.org/pub/ruby/2.2/ruby-2.2.3.tar.bz2
  sha256: c745cb98b29127d7f19f1bf9e0a63c384736f4d303b83c4f4bda3c2ee3c5e41f

test:
  commands:
    - ruby --version

requirements:
  build:
    - yaml
    - zlib

about:
  home: http://www.ruby-lang.org
  license: BSD
