package:
  name: glib
  version: 2.44.1

source:
  fn: glib-2.44.1.tar.xz 
  url: http://ftp.gnome.org/pub/GNOME/sources/glib/2.44/glib-2.44.1.tar.xz 

build:
  number: 1

requirements:
  build:
    - python
    - libffi
  run:
    - python
    - libffi

about:
  home: https://developer.gnome.org/glib/
  license: GPL
  summary: GLib provides the core application building blocks for libraries and applications written in C.
