package:
  name: petsc4py
  version: 3.4

source:
  fn: petsc4py-3.4.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-3.4.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - numpy
    - petsc 3.4*

  run:
    - python
    - numpy
    - petsc 3.4*

test:
  imports:
    - petsc4py
    - petsc4py.lib

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license: BSD License
  summary: 'PETSc for Python'
