package:
  name: scalapack
  version: 2.0.2

source:
  fn: scalapack-2.0.2.tgz
  url: http://www.netlib.org/scalapack/scalapack-2.0.2.tgz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - openblas
    - openmpi 1.8*
  run:
    - openblas
    - openmpi 1.8*

about:
  home: http://www.netlib.org/scalapack/
  license: modified BSD
  summary: ScaLAPACK is a library of high-performance linear algebra routines for parallel distributed memory machines. 
