package:
  name: gem-mail
  version: 2.6.3

build:
  number: 0

requirements:
  build:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -e "require 'mail'"

about:
  home: https://github.com/mikel/mail
  license: MIT
  summary: A Really Ruby Mail Library
