package:
  name: parmetis
  version: 4.0.3

source:
  fn: parmetis-4.0.3.tar.gz
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - cmake
    - openmpi
  run:
    - openmpi
    - metis-gkrand # metis.h is required

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
  license: University of Minnesota
  summary: ParMETIS is an MPI-based parallel library that implements a variety of algorithms for partitioning unstructured graphs, meshes, and for computing fill-reducing orderings of sparse matrices.
