package:
  name: hdf5-parallel
  version: 1.8.16

source:
  fn: hdf5-1.8.16.tar.bz2
  url: http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.16.tar.bz2

build:
  number: 0

requirements:
  build:
    - zlib
    - openmpi 1.8*
  run:
    - zlib
    - openmpi 1.8*

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
  summary: HDF5 is a data model, library, and file format for storing and managing data.
