package:
  name: instant
  version: "1.5.0"

source:
  fn: instant-1.5.0.tar.gz
  url: https://bitbucket.org/fenics-project/instant/downloads/instant-1.5.0.tar.gz
  md5: b744023ded27ee9df4a8d8c6698c0d58

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - cmake
    - swig

test:
  imports:
    - instant

  commands:
    - instant-clean
    - instant-showcache

  requires:
    - nose

about:
  home: http://www.fenicsproject.org
  license: BSD License or The GNU Lesser General Public License, version 3.0
  summary: 'Instant Inlining of C/C++ in Python'
