package:
  name: parmetis
  version: 4.0.2p5

source:
  fn: parmetis-4.0.2-p5.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/externalpackages/parmetis-4.0.2-p5.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - cmake 2.8*
    - openmpi 1.8*
    - metis 5.0*
  run:
    - openmpi 1.8*
    - metis 5.0*

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/parmetis/overview
  license: University of Minnesota
  summary: ParMETIS is an MPI-based parallel library that implements a variety of algorithms for partitioning unstructured graphs, meshes, and for computing fill-reducing orderings of sparse matrices.
