package:
  name: superlu_dist
  version: 4.0

source:
  fn: superlu_dist_4.0.tar.gz
  url: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_4.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - gcc
    - openblas
    - openmpi
    - metis-gkrand
    - parmetis
  run:
    - libgcc
    - openblas
    - openmpi
    - metis-gkrand
    - parmetis

about:
  home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
  license: University of California
  summary: SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations on high performance machines.
