package:
  name: buildbot-slave
  version: 0.8.12

source:
  fn: v0.8.12.tar.gz
  url: https://github.com/buildbot/buildbot/archive/v0.8.12.tar.gz
  md5: 751c76e79e38d04b32c95f0b34f720c8

build:
  number: 1

requirements:
  build:
    - pip
    - python
    - twisted >=8.0.0
  run:
    - python
    - twisted >=8.0.0

test:
  commands:
    - buildslave --help

about:
  home: http://buildbot.net/
  license: GPL2
  summary: Buildbot is an open-source framework for automating software build, test, and release processes.
