package:
  name: metis
  version: 5.1.0p1

source:
  fn: metis-5.1.0-p1.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/externalpackages/metis-5.1.0-p1.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake 2.8*

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
  license: Apache 2.0
  summary: Serial Graph Partitioning and Fill-reducing Matrix Ordering
