package:
  name: superlu_dist
  version: 3.3

source:
  fn: superlu_dist_3.3.tar.gz
  url: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/superlu_dist_3.3.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - openblas # [linux]
    - parmetis 4.0.2*
  run:
    - openblas # [linux]
    - parmetis 4.0.2*

about:
  home: http://crd-legacy.lbl.gov/~xiaoye/SuperLU/
  license: University of California
  summary: SuperLU is a general purpose library for the direct solution of large, sparse, nonsymmetric systems of linear equations on high performance machines.
