package:
  name: tuto-metis
  version: 5.1.0

source:
  fn: metis-5.1.0.tar.gz
  url: http://glaros.dtc.umn.edu/gkhome/fetch/sw/metis/metis-5.1.0.tar.gz

build:
  number: 0

requirements:
  build:
    - cmake

about:
  home: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview
  license: Apache 2.0
  summary: Serial Graph Partitioning and Fill-reducing Matrix Ordering
