package:
  name: mumps
  version: 4.10.0p3

source:
  fn: MUMPS_4.10.0-p3.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/externalpackages/MUMPS_4.10.0-p3.tar.gz

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - openblas #[linux]
    - scalapack 2.0*
    - parmetis 4.0.2*
  run:
    - openblas #[linux]
    - scalapack 2.0*
    - parmetis 4.0.2*

about:
  home: http://mumps.enseeiht.fr/
  license: Public domain
  summary: A parallel sparse direct solver
