package:
  name: petsc
  version: 3.4.5

source:
  fn: petsc-lite-3.4.5.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.4.5.tar.gz

build:
  number: 1 # [linux]
  number: 2 # [osx]
  binary_relocation: true

requirements:
  build:
    - python
    - cmake
    - mumps 4.10*
    - superlu_dist 3.3*
    - libgcc # [osx]
  run:
    - mumps 4.10*
    - superlu_dist 3.3*
    - libgcc # [osx]

about:
  home: http://www.mcs.anl.gov/petsc/
  license: BSD
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'
